version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: v4runa.log
    formatter: simple
    backupCount: 7
    when: midnight
root:
  level: INFO
  handlers: [console,logfile]

